// Export all types from core types
export * from './api.types';
export * from './auth.types';
export * from './common.types';
export * from './spare-parts.types';
export * from './payment.types';
export * from './analytics.types';

// Re-export commonly used types for convenience
export type {
  ApiResponse,
  ApiError,
  PaginationMeta,
  PaginatedResponse,
  LoadingState,
  AsyncState,
  SelectOption,
  FilterOption,
  SortOption,
  SearchParams,
  FormField,
  ValidationRule,
  FileUpload,
  UploadedFile,
  Notification,
  ThemeMode,
  ThemeSettings,
  Language,
  Currency,
  AppError,
  ChartData,
  ChartDataset,
  TableColumn,
  TableProps,
  ModalProps,
  BreadcrumbItem,
  MenuItem,
  StatCard,
  Status,
  Priority,
  Size,
  Color,
  Direction,
  Alignment,
  Justify,
  Wrap,
  Position,
  Display,
  Overflow,
  TextAlign,
  FontWeight,
  FontStyle,
  TextDecoration,
  TextTransform,
  Cursor,
  BorderStyle,
  BorderRadius,
  Shadow,
  ZIndex,
  Animation,
  Transition,
  MediaQuery,
  Breakpoints,
  BaseEntity,
  Timestamps,
  CreateRequest,
  UpdateRequest,
  DeleteRequest,
} from './common.types';

export type {
  User,
  UserRole,
  UserPreferences,
  LoginCredentials,
  RegisterCredentials,
  AuthResponse,
  TokenPayload,
  RefreshTokenRequest,
  RefreshTokenResponse,
  PasswordResetRequest,
  PasswordResetResponse,
  PasswordResetConfirm,
  AuthState,
  LoginFormData,
  RegisterFormData,
  ChangePasswordFormData,
  ForgotPasswordFormData,
  ResetPasswordFormData,
  AuthValidationErrors,
  AuthApiResponse,
  AuthMiddlewareOptions,
  AuthStorage,
  AuthContextType,
  UseAuthReturn,
  SecurityQuestion,
  SecurityQuestionAnswer,
  SecurityQuestionsSetup,
  PasswordResetWithQuestions,
  Permission,
  RolePermissions,
  UserSession,
} from './auth.types';
